### ISSUE TITLE
My first bug report...

### ISSUE THREAD

**Issue by embray** [kali-maa/astropy#55]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

```python
# Put your Python code snippet here.
```

**Comment by embray** [comment]
Ah, it took a few seconds but it worked =)

**Comment by pllim** [comment]
I am surprised they even use Docker, which caused it to be so slow, when there is no reason to.

There are 2 ways forward:

1. Use it as-is, slowness and everything.
2. I'll fork it and get rid of Docker (actions/first-interaction#39) and then we can use the version on my fork.

What do you think?

**Comment by embray** [comment]
It still only took 38 seconds. I think that's good enough.

I do wish there were more options to personalize the message (eg. say the
person's username). I opened and issue for that and might make a PR later.
Let's hold off on doing anything that would require any maintenance on our
part for now.
