### ISSUE TITLE
Crash test dummy material

### ISSUE THREAD

**Issue by jhunkeler** [kali-maa/astropy#59]
### Description

The ballistic gel was replaced with whole grains.

### Expected behavior

The ballistic gel should have been made of ballistic gel.

### Actual behavior

The dummy became breakfast on impact.
### Steps to Reproduce

1. Load dummy into cannon
2. Fire dummy at giant bowl
3. Bowl is filled with whole grains

```python
>>> bowl.contents
<Ballistic.Cereal>
```

### System Details

DummySploder9000 rev. 66c with all leather interior

**Comment by pllim** [comment]
It works! The text is a little outdated but I have sync-ed with upstream since. Thanks for your help, Joe!
