### ISSUE TITLE
kali maa shakti de

### ISSUE THREAD

**Issue by nstarman** [kali-maa/astropy#69]
### Description

https://movies.stackexchange.com/questions/43054/english-translation-of-the-temple-chants-in-indiana-jones-and-the-temple-of-doom

### Additional context

"bali chadhogay"    = "(you) will be sacrificed"
"bali mangti kali maa"  = "mother kali wants offering/sacrifice"
"mukti degi kalli maa"  = "mother kali will give salvation"
"kali maa"       = "Mother kali" 
"kali maa shakti de"  = "Mother kali give (me) power"
"bali chadhau tere aage"= " (I) offer sacrifice before you"
"swikar karo"       = "(please) accept"
(*removes heart*....boy screams, girl screams)
"ab iski jaan meri muthi main hai" = "now his life is in my hands" (shows Myogenic contraction of heart to crowd) 
"bali chadhado"    = "do the sacrifice" (sacrifice him)
(*boy dies chanting..*)

**Comment by nstarman** [comment]
That was definitely faster than Docker, but not 1-2 s.

**Comment by pllim** [comment]
Hah hah... 1-2 s is the script run time reported in the log. If you add other overhead, I think it's a bit more. Why do I have deja vu.
